django_pos/django_pos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # Authentication: Login and Logout
    path('', include('authentication.urls')),
    # Index
    path('', include('pos.urls')),
    # Products
    path('products/', include('products.urls')),
    # Customers
    path('customers/', include('customers.urls')),
    # Sales
    path('sales/', include('sales.urls')),
]

django_pos/sales/urls.py
from django.urls import path

from . import views

app_name = "sales"
urlpatterns = [
    # List sales
    path('', views.sales_list_view, name='sales_list'),
    # Add sale
    path('add', views.sales_add_view, name='sales_add'),
    # Details sale
    path('details/<str:sale_id>',
         views.sales_details_view, name='sales_details'),
    # Sale receipt PDF
    path("pdf/<str:sale_id>",
         views.receipt_pdf_view, name="sales_receipt_pdf"),
]

django_pos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Include the default password reset URLs from Django's auth system
    path('accounts/', include('django.contrib.auth.urls')),
]

django_pos/sales/models.py
from django.db import models
import django.utils.timezone
from customers.models import Customer
from products.models import Product


class Sale(models.Model):
    date_added = models.DateTimeField(default=django.utils.timezone.now)
    customer = models.ForeignKey(
        Customer, models.DO_NOTHING, db_column='customer')
    sub_total = models.FloatField(default=0)
    grand_total = models.FloatField(default=0)
    tax_amount = models.FloatField(default=0)
    tax_percentage = models.FloatField(default=0)
    amount_payed = models.FloatField(default=0)
    amount_change = models.FloatField(default=0)

    class Meta:
        db_table = 'Sales'

    def __str__(self) -> str:
        return "Sale ID: " + str(self.id) + " | Grand Total: " + str(self.grand_total) + " | Datetime: " + str(self.date_added)

    def sum_items(self):
        details = SaleDetail.objects.filter(sale=self.id)
        return sum([d.quantity for d in details])


class SaleDetail(models.Model):
    sale = models.ForeignKey(
        Sale, models.DO_NOTHING, db_column='sale')
    product = models.ForeignKey(
        Product, models.DO_NOTHING, db_column='product')
    price = models.FloatField()
    quantity = models.IntegerField()
    total_detail = models.FloatField()

    class Meta:
        db_table = 'SaleDetails'

    def __str__(self) -> str:
        return "Detail ID: " + str(self.id) + " Sale ID: " + str(self.sale.id) + " Quantity: " + str(self.quantity)

django_pos/sales/views.py
import os

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django_pos.wsgi import *
from django_pos import settings
from django.template.loader import get_template
from customers.models import Customer
from products.models import Product
from weasyprint import HTML, CSS
from .models import Sale, SaleDetail
import json


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


@login_required(login_url="/accounts/login/")
def sales_list_view(request):
    context = {
        "active_icon": "sales",
        "sales": Sale.objects.all()
    }
    return render(request, "sales/sales.html", context=context)


@login_required(login_url="/accounts/login/")
def sales_add_view(request):
    context = {
        "active_icon": "sales",
        "customers": [c.to_select2() for c in Customer.objects.all()]
    }

    if request.method == 'POST':
        if is_ajax(request=request):
            # Save the POST arguments
            data = json.load(request)

            sale_attributes = {
                "customer": Customer.objects.get(id=int(data['customer'])),
                "sub_total": float(data["sub_total"]),
                "grand_total": float(data["grand_total"]),
                "tax_amount": float(data["tax_amount"]),
                "tax_percentage": float(data["tax_percentage"]),
                "amount_payed": float(data["amount_payed"]),
                "amount_change": float(data["amount_change"]),
            }
            try:
                # Create the sale
                new_sale = Sale.objects.create(**sale_attributes)
                new_sale.save()
                # Create the sale details
                products = data["products"]

                for product in products:
                    detail_attributes = {
                        "sale": Sale.objects.get(id=new_sale.id),
                        "product": Product.objects.get(id=int(product["id"])),
                        "price": product["price"],
                        "quantity": product["quantity"],
                        "total_detail": product["total_product"]
                    }
                    sale_detail_new = SaleDetail.objects.create(
                        **detail_attributes)
                    sale_detail_new.save()

                print("Sale saved")

                messages.success(
                    request, 'Sale created successfully!', extra_tags="success")

            except Exception as e:
                messages.success(
                    request, 'There was an error during the creation!', extra_tags="danger")

        return redirect('sales:sales_list')

    return render(request, "sales/sales_add.html", context=context)


@login_required(login_url="/accounts/login/")
def sales_details_view(request, sale_id):
    """
    Args:
        request:
        sale_id: ID of the sale to view
    """
    try:
        # Get the sale
        sale = Sale.objects.get(id=sale_id)

        # Get the sale details
        details = SaleDetail.objects.filter(sale=sale)

        context = {
            "active_icon": "sales",
            "sale": sale,
            "details": details,
        }
        return render(request, "sales/sales_details.html", context=context)
    except Exception as e:
        messages.success(
            request, 'There was an error getting the sale!', extra_tags="danger")
        print(e)
        return redirect('sales:sales_list')


@login_required(login_url="/accounts/login/")
def receipt_pdf_view(request, sale_id):
    """
    Args:
        request:
        sale_id: ID of the sale to view the receipt
    """
    # Get the sale
    sale = Sale.objects.get(id=sale_id)

    # Get the sale details
    details = SaleDetail.objects.filter(sale=sale)

    template = get_template("sales/sales_receipt_pdf.html")
    context = {
        "sale": sale,
        "details": details
    }
    html_template = template.render(context)

    # CSS Boostrap
    css_url = os.path.join(
        settings.BASE_DIR, 'static/css/receipt_pdf/bootstrap.min.css')

    # Create the pdf
    pdf = HTML(string=html_template).write_pdf(stylesheets=[CSS(css_url)])

    return HttpResponse(pdf, content_type="application/pdf")

django_pos/templates/sales/sales.html
{% extends "pos/base.html" %}
{% load static %}
<!-- Page title  -->
{% block title %}Sales{% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<!-- Datatables -->
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css ' %}" rel="stylesheet">
<link href="{% static 'css/pagination_buttons.css ' %}" rel="stylesheet">
{% endblock stylesheets %}

<!-- Page Heading -->
{% block heading %}Sales{% endblock heading %}

<!-- Page content  -->
{% block content %}

    <!--Create new sale-->
    <div class="row ml-0 mb-3">
        <a href="{% url 'sales:sales_add' %}">
            <button type="button" class="btn btn-success font-weight-bold">
                    <i class="fas fa-plus mr-2"></i>
                    Create new sale
            </button>
        </a>
    </div>

    <!-- DataTable -->
    <div class="card shadow mb-12">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Customers</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th style="width:5%">#</th>
                            <th style="width:15%">ID</th>
                            <th style="width:25%">Date</th>
                            <th style="width:20%">Customer</th>
                            <th class="text-center" style="width:10%">Total</th>
                            <th class="text-center" style="width:5%">Items</th>
                            <th class="text-center" style="width:10%">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for s in sales %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{s.id}}</td>
                            <td>{{s.date_added}}</td>
                            <td>{{s.customer.get_full_name}}</td>
                            <td class="text-right">Rs {{s.grand_total}}</td>
                            <td class="text-center">{{s.sum_items}}</td>
                            <td class="text-center">
                                <!--View-->
                                <a href="{% url 'sales:sales_details' s.id %}" class="text-decoration-none">
                                    <button type="button" class="btn btn-info btn-sm" data-bs-toggle="tooltip" title="Update sale">
                                        <i class="fas fa-eye"></i>
                                    </button>
                                </a>
                                <!--Print receipt-->
                                <a href="{% url 'sales:sales_receipt_pdf' s.id %}" class="text-decoration-none">
                                    <button type="button" class="btn btn-dark btn-sm" data-bs-toggle="tooltip" title="View Receipt">
                                        <i class="fas fa-receipt"></i>
                                    </button>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<!-- Datatables -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<!--Datatable buttons-->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.3/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.3/js/buttons.colVis.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.3/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.3/js/buttons.print.min.js"></script>
<!--Moment JS-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>

<!--Datatables-->
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
        tblCategories = $('#dataTable').DataTable({
            dom: 'Bfrtip', // Buttons are draw at this element
            buttons: [
                {
                extend: 'print',
                text: 'Print <i class="fas fa-file ml-2"></i>',
                titleAttr: 'Print',
                className: 'btn btn-info',
                exportOptions: {
                    columns: [ 0, 1, 2, 3 ,4, 5]
                }            
                },
                {
                    extend: 'excelHtml5',
                    text: 'Download Excel <i class="fas fa-file-excel ml-2"></i>',
                    titleAttr: 'Download Excel',
                    className: 'btn btn-success ml-2',
                    exportOptions: {
                        columns: [ 0, 1, 2, 3 ,4, 5 ]
                    } 
                },
                {
                    extend: 'pdfHtml5',
                    text: 'Download PDF <i class="fas fa-file-pdf ml-2"></i>',
                    titleAttr: 'Download PDF',
                    className: 'btn btn-danger ml-2',
                    download: 'open',
                    orientation: 'vertical',
                    pageSize: 'A4',
                    title: '*',
                    exportOptions: {
                        columns: [ 0, 1, 2, 3 ,4 ,5]
                    },
                    customize: function (doc) {
                        doc.styles = {
                            header: {
                                fontSize: 18,
                                bold: true,
                                alignment: 'center'
                            },
                            subheader: {
                                fontSize: 13,
                                bold: true
                            },
                            quote: {
                                italics: true
                            },
                            small: {
                                fontSize: 8
                            },
                            tableHeader: {
                                bold: true,
                                fontSize: 11,
                                color: 'white',
                                fillColor: '#2d4154',
                                alignment: 'center'
                            }
                        };
                        doc.content[1].table.widths = ['10%', '10%', '30%', '20%', '20%', '10%'];
                        doc.content[1].margin = [0, 35, 0, 0];
                        doc.content[1].layout = {};
                        doc['footer'] = (function (page, pages) {
                            return {
                                columns: [
                                    {
                                        alignment: 'left',
                                        text: ['Creation date: ', {text: moment().format('MM-DD-YYYY (HH:mm:ss)')}]
                                    },
                                    {
                                        alignment: 'right',
                                        text: ['page ', {text: page.toString()}, ' de ', {text: pages.toString()}]
                                    }
                                ],
                                margin: 20
                            }
                        });

                    }
                }
            ],
            deferRender: true,
            columnDefs: [
                {
                    targets: [-1], // column index (start from 0)
                    orderable: false, // set orderable false for selected columns
                }
            ],
        });
    });
</script>
{% endblock javascripts %}

django_pos/templates/sales/sales_details.html
{% extends "pos/base.html" %}
{% load static %}
<!-- Page title  -->
{% block title %}Sale details{% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<!-- Datatables -->
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css ' %}" rel="stylesheet">
<!--Select2 CSS-->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@1.5.2/dist/select2-bootstrap4.min.css">
<!--Bootstrap Touchspin-->
<link rel="stylesheet" href="{% static 'assets/bootstrap-touchspin-master/src/jquery.bootstrap-touchspin.css' %}">
{% endblock stylesheets %}

<!-- Page Heading -->
{% block heading %}Sale ID: {{sale.id}}, details{% endblock heading %}

<!-- Page content  -->
{% block content %}
<!--Go back-->
<div class="row ml-0 mb-3">
    <a href="{% url 'sales:sales_list' %}">
        <button type="button" class="btn btn-info font-weight-bold">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            Go back
        </button>
    </a>
</div>

<!--Sale products and details-->
<form action="{% url 'sales:sales_add' %}" class="saleForm" method="post">
    <div class="row mt-3">
        <div class="card col-md-12">
            <div class="card-body ml-0">
                <div class="row">
                    <!--Left column-->
                    <div class="col-md-9 pl-0">
                        <div class="card card-secondary">
                            <div class="card-header">Sale products</div>
                            
                            <div class="card-body">
                                <!--Products table-->
                                <div class="card-body table-responsive p-0">
                                    <table class="table table-hover text-nowrap" id="table_products">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Name</th>
                                                <th>Price</th>
                                                <th>Quantity</th>
                                                <th>Total</th>
                                                </tr>
                                            </thead>
                                        <tbody>
                                            {% for detail in details %}
                                            <tr>
                                                <td>{{forloop.counter}}</td>
                                                <td>{{detail.product.name}}</td>
                                                <td>Rs {{detail.price}}</td>
                                                <td class="text-center">{{detail.quantity}}</td>
                                                <td>Rs {{detail.total_detail}}</td>
                                            </tr>
                                            {% endfor %}
                                            <tr>
                                                <td colspan="4" class="text-right pr-2"><b>Subtotal</b></td>
                                                <td class="text-right pr-2">Rs {{sale.sub_total|floatformat:2}}</td>
                                            </tr>
                                            <tr>
                                                <td colspan="4" class="text-right pr-2"><b>Tax Inclusive ({{sale.tax_percentage}}%)</b></td>
                                                <td class="text-right pr-2">Rs {{sale.tax_amount|floatformat:2}}</td>
                                            </tr>
                                            <tr>
                                                <td colspan="4" class="text-right pr-2"><b>Grand Total</b></td>
                                                <td class="text-right pr-2">Rs {{sale.grand_total}}</td>
                                            </tr>
                                            <tr>
                                                <td colspan="4" class="text-right pr-2"><b>Amount payed</b></td>
                                                <td class="text-right pr-2">Rs {{sale.amount_payed}}</td>
                                            </tr>
                                            <tr>
                                                <td colspan="4" class="text-right pr-2"><b>Change</b></td>
                                                <td class="text-right pr-2">Rs {{sale.amount_change}}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <!--End Products table-->
                            </div>
                        </div>
                    </div>
                    <!--End Left column-->

                    <!--Righ column-->
                    <div class="col-md-3 pr-0">
                        <div class="card card-secondary">
                            <div class="card-header">Sale details</div>
                            <div class="card-body">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="customer">Customer</label>
                                    <select name="customer" class="form-control" id="searchbox_customers" disabled readonly>
                                        <option value="{{sale.customer.id}}">{{sale.customer.get_full_name}}</option>
                                    </select>
                                <div class="form-group mt-4">
                                    <label>Subtotal</label>
                                    <div class="input-group">
                                        <input name="sub_total" class="form-control" value="{{sale.sub_total}}" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Tax Inclusive (%)</label>
                                    <div class="input-group">
                                        <input name="tax_percentage" class="form-control" value="{{sale.tax_percentage}}" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Tax Amount</label>
                                    <div class="input-group">
                                        <input name="tax_amount" class="form-control" value="{{sale.tax_amount}}" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Grand Total</label>
                                    <div class="input-group">
                                        <input name="grand_total" class="form-control" value="{{sale.grand_total}}" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Amount payed</label>
                                    <div class="input-group">
                                        <input name="amount_payed" class="form-control" value="{{sale.amount_payed}}" readonly>
                                    </div>
                                </div>

                            </div>
                            <!--End card-body-->
                    </div>
                    <!--End Right column-->
                </div>
                <!--End row-->
            </div>
            <!--End card-body-->
        </div>

    </div>
</form>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<!-- Datatables -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<!--Select2-->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" defer></script>
<!--Bootstrap Touchspin-->
<script src="{% static 'assets/bootstrap-touchspin-master/src/jquery.bootstrap-touchspin.js' %}"></script>
<!--Sweet Alert-->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.6.15/dist/sweetalert2.all.min.js"></script>

<script>
    
// Products datatable

tblProducts = $('#table_products').DataTable({
});
                    
</script>
{% endblock javascripts %}

django_pos/templates/sales/sales_receipt_pdf.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sale Receipt PDF</title>
    <style>

        * {
            color: black;
        }

        body {
            font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
            padding: 0;
            margin: 0;
            color: black;
        }

        .name-company {
            font-size: 25px;
            font-weight: bold;
            text-transform: uppercase;
        }

        table thead tr th {
            border: 1px solid black !important;
            padding: 3px;
        }

        table tbody tr td {
            border: 1px solid black;
            padding: 3px;
        }

        .img-logo {
            margin-top: 10px;
            width: 75px;
            height: 75px;
            margin-bottom: 10px;
        }

    </style>
</head>
<body>
<div class="container-fluid">
    <div class="row border border-dark">
        <div class="col-6">
            <p class="Wadani Group" style="font-size: 24px;"><b>Wadani Group</b></p>
            <p><b>Habib University</b></p>
            <p><b>Pehlwan Goth, Near Farhan Biryani</b></p>
            <p><b>Phone:</b> (+92) 333-696969</p>
        </div>
        
        <div class="col-6 border-left border-dark">
            <p><b>Date:</b> {{sale.date_added}}</p>
            <p><b>Sale ID:</b> {{sale.id}}</p>
            <p><b>Customer:</b> {{sale.customer.get_full_name}}</p>
        </div>
    </div>

    <br>

    <!--Tabla de productos-->
    <table class="table" style="width: 100%;">
        <thead>
        <tr style="border: 1px solid black;">
            <th style="width: 5%;" class="text-center">#</th>
            <th style="width: 40%;" class="text-left pl-2">Product</th>
            <th style="width: 5%;" class="text-center">Quantity</th>
            <th style="width: 20%;" class="text-right pr-2">Price</th>
            <th style="width: 20%;" class="text-right pr-2">Total</th>
        </tr>
        </thead>
        <tbody>
        {% for d in details %}
            <tr>
                <td class="text-center">{{forloop.counter}}</td>
                <td class="text-left pl-2">{{d.product.name}}</td>
                <td class="text-center">{{d.quantity}}</td>
                <td class="text-right pr-2">Rs {{d.price}}</td>
                <td class="text-right pr-2">Rs {{d.total_detail}}</td>
            </tr>
        {% endfor %}
        <tr>
            <td colspan="4" class="text-right pr-2"><b>Subtotal</b></td>
            <td class="text-right pr-2">Rs {{sale.sub_total|floatformat:2}}</td>
        </tr>
        <tr>
            <td colspan="4" class="text-right pr-2"><b>Tax Inclusive ({{sale.tax_percentage}}%)</b></td>
            <td class="text-right pr-2">Rs {{sale.tax_amount|floatformat:2}}</td>
        </tr>
        <tr>
            <td colspan="4" class="text-right pr-2"><b>Grand Total</b></td>
            <td class="text-right pr-2">Rs {{sale.grand_total}}</td>
        </tr>
        <tr>
            <td colspan="4" class="text-right pr-2"><b>Amount payed</b></td>
            <td class="text-right pr-2">Rs {{sale.amount_payed}}</td>
        </tr>
        <tr>
            <td colspan="4" class="text-right pr-2"><b>Change</b></td>
            <td class="text-right pr-2">Rs {{sale.amount_change}}</td>
        </tr>
        <tr>
            <td colspan="5">
                <p class="text-uppercase font-weight-bold text-center">
                    Thank you for your preference!
                </p>
            </td>
        </tr>
        </tbody>
    </table>
</div>
</body>
</html>