django_pos/django_pos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # Authentication: Login and Logout
    path('', include('authentication.urls')),
    # Index
    path('', include('pos.urls')),
    # Products
    path('products/', include('products.urls')),
    # Customers
    path('customers/', include('customers.urls')),
    # Sales
    path('sales/', include('sales.urls')),
]

django_pos/products/urls.py
from django.urls import path

from . import views

app_name = "products"
urlpatterns = [
    # List categories
    path('categories', views.categories_list_view, name='categories_list'),
    # Add category
    path('categories/add', views.categories_add_view, name='categories_add'),
    # Update category
    path('categories/update/<str:category_id>',
         views.categories_update_view, name='categories_update'),
    # Delete category
    path('categories/delete/<str:category_id>',
         views.categories_delete_view, name='categories_delete'),

    # List products
    path('', views.products_list_view, name='products_list'),
    # Add product
    path('add', views.products_add_view, name='products_add'),
    # Update product
    path('update/<str:product_id>',
         views.products_update_view, name='products_update'),
    # Delete product
    path('delete/<str:product_id>',
         views.products_delete_view, name='products_delete'),
    # Get products AJAX
    path("get", views.get_products_ajax_view, name="get_products"),
]

django_pos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Include the default password reset URLs from Django's auth system
    path('accounts/', include('django.contrib.auth.urls')),
]

django_pos/products/models.py
from django.db import models
from django.forms import model_to_dict


class Category(models.Model):
    STATUS_CHOICES = (  # new
        ("ACTIVE", "Active"),
        ("INACTIVE", "Inactive")
    )

    name = models.CharField(max_length=256)
    description = models.TextField(max_length=256)
    status = models.CharField(
        choices=STATUS_CHOICES,
        max_length=100,
        verbose_name="Status of the category",
    )

    class Meta:
        # Table's name
        db_table = "Category"
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    STATUS_CHOICES = (  # new
        ("ACTIVE", "Active"),
        ("INACTIVE", "Inactive")
    )

    name = models.CharField(max_length=256)
    description = models.TextField(max_length=256)
    status = models.CharField(
        choices=STATUS_CHOICES,
        max_length=100,
        verbose_name="Status of the product",
    )
    category = models.ForeignKey(
        Category, related_name="category", on_delete=models.CASCADE, db_column='category')

    price = models.FloatField(default=0)

    class Meta:
        # Table's name
        db_table = "Product"

    def __str__(self) -> str:
        return self.name

    def to_json(self):
        item = model_to_dict(self)
        item['id'] = self.id
        item['text'] = self.name
        item['category'] = self.category.name
        item['quantity'] = 1
        item['total_product'] = 0
        return item

django_pos/products/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .models import Category, Product


@login_required(login_url="/accounts/login/")
def categories_list_view(request):
    context = {
        "active_icon": "products_categories",
        "categories": Category.objects.all()
    }
    return render(request, "products/categories.html", context=context)


@login_required(login_url="/accounts/login/")
def categories_add_view(request):
    context = {
        "active_icon": "products_categories",
        "category_status": Category.status.field.choices
    }

    if request.method == 'POST':
        # Save the POST arguments
        data = request.POST

        attributes = {
            "name": data['name'],
            "status": data['state'],
            "description": data['description']
        }

        # Check if a category with the same attributes exists
        if Category.objects.filter(**attributes).exists():
            messages.error(request, 'Category already exists!',
                           extra_tags="warning")
            return redirect('products:categories_add')

        try:
            # Create the category
            new_category = Category.objects.create(**attributes)

            # If it doesn't exist, save it
            new_category.save()

            messages.success(request, 'Category: ' +
                             attributes["name"] + ' created successfully!', extra_tags="success")
            return redirect('products:categories_list')
        except Exception as e:
            messages.success(
                request, 'There was an error during the creation!', extra_tags="danger")
            print(e)
            return redirect('products:categories_add')

    return render(request, "products/categories_add.html", context=context)


@login_required(login_url="/accounts/login/")
def categories_update_view(request, category_id):
    """
    Args:
        request:
        category_id : The category's ID that will be updated
    """

    # Get the category
    try:
        # Get the category to update
        category = Category.objects.get(id=category_id)
    except Exception as e:
        messages.success(
            request, 'There was an error trying to get the category!', extra_tags="danger")
        print(e)
        return redirect('products:categories_list')

    context = {
        "active_icon": "products_categories",
        "category_status": Category.status.field.choices,
        "category": category
    }

    if request.method == 'POST':
        try:
            # Save the POST arguments
            data = request.POST

            attributes = {
                "name": data['name'],
                "status": data['state'],
                "description": data['description']
            }

            # Check if a category with the same attributes exists
            if Category.objects.filter(**attributes).exists():
                messages.error(request, 'Category already exists!',
                               extra_tags="warning")
                return redirect('products:categories_add')

            # Get the category to update
            category = Category.objects.filter(
                id=category_id).update(**attributes)

            category = Category.objects.get(id=category_id)

            messages.success(request, '¡Category: ' + category.name +
                             ' updated successfully!', extra_tags="success")
            return redirect('products:categories_list')
        except Exception as e:
            messages.success(
                request, 'There was an error during the elimination!', extra_tags="danger")
            print(e)
            return redirect('products:categories_list')

    return render(request, "products/categories_update.html", context=context)


@login_required(login_url="/accounts/login/")
def categories_delete_view(request, category_id):
    """
    Args:
        request:
        category_id : The category's ID that will be deleted
    """
    try:
        # Get the category to delete
        category = Category.objects.get(id=category_id)
        category.delete()
        messages.success(request, '¡Category: ' + category.name +
                         ' deleted!', extra_tags="success")
        return redirect('products:categories_list')
    except Exception as e:
        messages.success(
            request, 'There was an error during the elimination!', extra_tags="danger")
        print(e)
        return redirect('products:categories_list')


@login_required(login_url="/accounts/login/")
def products_list_view(request):
    context = {
        "active_icon": "products",
        "products": Product.objects.all()
    }
    return render(request, "products/products.html", context=context)


@login_required(login_url="/accounts/login/")
def products_add_view(request):
    context = {
        "active_icon": "products_categories",
        "product_status": Product.status.field.choices,
        "categories": Category.objects.all().filter(status="ACTIVE")
    }

    if request.method == 'POST':
        # Save the POST arguments
        data = request.POST

        attributes = {
            "name": data['name'],
            "status": data['state'],
            "description": data['description'],
            "category": Category.objects.get(id=data['category']),
            "price": data['price']
        }

        # Check if a product with the same attributes exists
        if Product.objects.filter(**attributes).exists():
            messages.error(request, 'Product already exists!',
                           extra_tags="warning")
            return redirect('products:products_add')

        try:
            # Create the product
            new_product = Product.objects.create(**attributes)

            # If it doesn't exist, save it
            new_product.save()

            messages.success(request, 'Product: ' +
                             attributes["name"] + ' created successfully!', extra_tags="success")
            return redirect('products:products_list')
        except Exception as e:
            messages.success(
                request, 'There was an error during the creation!', extra_tags="danger")
            print(e)
            return redirect('products:products_add')

    return render(request, "products/products_add.html", context=context)


@login_required(login_url="/accounts/login/")
def products_update_view(request, product_id):
    """
    Args:
        request:
        product_id : The product's ID that will be updated
    """

    # Get the product
    try:
        # Get the product to update
        product = Product.objects.get(id=product_id)
    except Exception as e:
        messages.success(
            request, 'There was an error trying to get the product!', extra_tags="danger")
        print(e)
        return redirect('products:products_list')

    context = {
        "active_icon": "products",
        "product_status": Product.status.field.choices,
        "product": product,
        "categories": Category.objects.all()
    }

    if request.method == 'POST':
        try:
            # Save the POST arguments
            data = request.POST

            attributes = {
                "name": data['name'],
                "status": data['state'],
                "description": data['description'],
                "category": Category.objects.get(id=data['category']),
                "price": data['price']
            }

            # Check if a product with the same attributes exists
            if Product.objects.filter(**attributes).exists():
                messages.error(request, 'Product already exists!',
                               extra_tags="warning")
                return redirect('products:products_add')

            # Get the product to update
            product = Product.objects.filter(
                id=product_id).update(**attributes)

            product = Product.objects.get(id=product_id)

            messages.success(request, '¡Product: ' + product.name +
                             ' updated successfully!', extra_tags="success")
            return redirect('products:products_list')
        except Exception as e:
            messages.success(
                request, 'There was an error during the update!', extra_tags="danger")
            print(e)
            return redirect('products:products_list')

    return render(request, "products/products_update.html", context=context)


@login_required(login_url="/accounts/login/")
def products_delete_view(request, product_id):
    """
    Args:
        request:
        product_id : The product's ID that will be deleted
    """
    try:
        # Get the product to delete
        product = Product.objects.get(id=product_id)
        product.delete()
        messages.success(request, '¡Product: ' + product.name +
                         ' deleted!', extra_tags="success")
        return redirect('products:products_list')
    except Exception as e:
        messages.success(
            request, 'There was an error during the elimination!', extra_tags="danger")
        print(e)
        return redirect('products:products_list')


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


@login_required(login_url="/accounts/login/")
def get_products_ajax_view(request):
    if request.method == 'POST':
        if is_ajax(request=request):
            data = []

            products = Product.objects.filter(
                name__icontains=request.POST['term'])
            for product in products[0:10]:
                item = product.to_json()
                data.append(item)

            return JsonResponse(data, safe=False)

django_pos/templates/products/categories.html
{% extends "pos/base.html" %}
{% load static %}
<!-- Page title  -->
{% block title %}Product categories{% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<!-- Datatables -->
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css ' %}" rel="stylesheet">
<link href="{% static 'css/pagination_buttons.css ' %}" rel="stylesheet">
{% endblock stylesheets %}

<!-- Page Heading -->
{% block heading %}Product categories{% endblock heading %}

<!-- Page content  -->
{% block content %}

    <!--Create new category-->
    <div class="row ml-0 mb-3">
        <a href="{% url 'products:categories_add' %}">
            <button type="button" class="btn btn-success font-weight-bold">
                    <i class="fas fa-plus mr-2"></i>
                    Create new category
            </button>
        </a>
    </div>

    <!-- DataTable -->
    <div class="card shadow mb-12">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Categories</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th style="width:7%">#</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th class="text-center" style="width:15%">Status</th>
                            <th class="text-center" style="width:15%">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in categories %}
                        <tr>
                            <td>{{c.id}}</td>
                            <td>{{forloop.counter}}</td>
                            <td>{{c.name}}</td>
                            <td>{{c.description}}</td>
                            {% if c.status == "ACTIVE" %}
                            <td class="text-center">
                                <span class="badge badge-success" style="font-size:0.8em;">{{c.status}}</span>
                            </td>
                            {% elif c.status == "INACTIVE" %}
                            <td class="text-center">
                                <span class="badge badge-danger" style="font-size:0.8em;">{{c.status}}</span>
                            </td>
                            {% endif %}
                            <td class="text-center">
                                <!--Update-->
                                <a href="{% url 'products:categories_update' c.id %}" class="text-decoration-none">
                                    <button type="button" class="btn btn-warning btn-sm" data-bs-toggle="tooltip" title="Update category">
                                        <i class="fas fa-pen"></i>
                                    </button>
                                </a>
                                <!--Delete modal-->
                                <!-- Button trigger modal -->
                                <a class="text-decoration-none">
                                    <button rel="delete" type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </a>
                                    
                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Delete category</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div id="updateThisText" class="modal-body">
                                            Are you sure you want to delete the category: {{c.name}}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                            <a id="updateThisURL" href="{% url 'products:categories_delete' c.id %}" class="text-decoration-none">
                                                <button type="button"  class="btn btn-danger">Delete</button>
                                            </a>
                                        </div>
                                    </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<!-- Datatables -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<!--Datatable buttons-->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.3/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.3/js/buttons.colVis.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.3/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.3/js/buttons.print.min.js"></script>
<!--Moment JS-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>

<!--Datatables-->
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
        tblCategories = $('#dataTable').DataTable({
            dom: 'Bfrtip', // Buttons are draw at this element
            buttons: [
                {
                extend: 'print',
                text: 'Print <i class="fas fa-file ml-2"></i>',
                titleAttr: 'Print',
                className: 'btn btn-info',
                exportOptions: {
                    columns: [ 0, 1, 2, 3 ,4 ]
                }            
                },
                {
                    extend: 'excelHtml5',
                    text: 'Download Excel <i class="fas fa-file-excel ml-2"></i>',
                    titleAttr: 'Download Excel',
                    className: 'btn btn-success ml-2',
                    exportOptions: {
                        columns: [ 0, 1, 2, 3 ,4 ]
                    } 
                },
                {
                    extend: 'pdfHtml5',
                    text: 'Download PDF <i class="fas fa-file-pdf ml-2"></i>',
                    titleAttr: 'Download PDF',
                    className: 'btn btn-danger ml-2',
                    download: 'open',
                    orientation: 'vertical',
                    pageSize: 'A4',
                    title: '*',
                    exportOptions: {
                        columns: [ 0, 1, 2, 3 ,4 ]
                    },
                    customize: function (doc) {
                        doc.styles = {
                            header: {
                                fontSize: 18,
                                bold: true,
                                alignment: 'center'
                            },
                            subheader: {
                                fontSize: 13,
                                bold: true
                            },
                            quote: {
                                italics: true
                            },
                            small: {
                                fontSize: 8
                            },
                            tableHeader: {
                                bold: true,
                                fontSize: 11,
                                color: 'white',
                                fillColor: '#2d4154',
                                alignment: 'center'
                            }
                        };
                        doc.content[1].table.widths = ['10%', '10%', '30%', '30%', '20%'];
                        doc.content[1].margin = [0, 35, 0, 0];
                        doc.content[1].layout = {};
                        doc['footer'] = (function (page, pages) {
                            return {
                                columns: [
                                    {
                                        alignment: 'left',
                                        text: ['Creation date: ', {text: moment().format('MM-DD-YYYY (HH:mm:ss)')}]
                                    },
                                    {
                                        alignment: 'right',
                                        text: ['page ', {text: page.toString()}, ' de ', {text: pages.toString()}]
                                    }
                                ],
                                margin: 20
                            }
                        });

                    }
                }
            ],
            deferRender: true,
            columnDefs: [
                {
                    targets: [0],
                    visible: false,
                    searchable: false,
                },
                {
                    targets: [-1], // column index (start from 0)
                    orderable: false, // set orderable false for selected columns
                }
            ],
        });
    });

    // Alert when trying to delete a category
    $('#dataTable tbody')
    // Event when whe try to delete a category
    // We update the text, and href of the modal delete button
    .on('click', 'button[rel="delete"]', function () {
    // Row variable
    var tr = tblCategories.cell($(this).closest('td, li')).index();
    row_data = ( tblCategories.row(tr.row).data());
    category_id = row_data[0];
    category_name = row_data[2]
    new_delete_url  = 'categories/delete/' + category_id;
    document.getElementById("updateThisText").innerHTML = "Are you sure you want to delete the category:  " + category_name + "?";
    document.getElementById("updateThisURL").href=new_delete_url;
    });
</script>
{% endblock javascripts %}

django_pos/templates/products/categories_update.html
{% extends "pos/base.html" %}

<!-- Page title  -->
{% block title %}Update category{% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

<!-- Page Heading -->
{% block heading %}Update category{% endblock heading %}

<!-- Page content  -->
{% block content %}
<!--Go back-->
<div class="row ml-0 mb-3">
    <a href="{% url 'products:categories_list' %}">
        <button type="button" class="btn btn-info font-weight-bold">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            Go back
        </button>
    </a>
</div>

<div class="row">
    <div class="card col-md-8">
        <div class="card-body">
            <form action="{% url 'products:categories_update' category.id %}"  method="post">
                {% csrf_token %}
                <div class="form-row">
                    
                    <div class="form-group col-md-8">
                        <label for="inputDescription">Name</label>
                        <input type="text" class="form-control" name="name" value="{{category.name}}" required>
                    </div>
                    
                    <div class="form-group col-md-4">
                        <label for="state">State</label>
                        <select name="state" class="form-control" required>
                            {% for status in category_status %}
                                {% if status.0 == category.status %}
                                <option value="{{status.0}}" selected>{{status.1}}</option>
                                {% else %}
                                <option value="{{status.0}}">{{status.1}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label for="inputDescription">Description</label>
                        <input type="text" name="description" class="form-control" value="{{category.description}}" required>
                    </div>
                </div>
               
                <button type="submit" class="btn btn-success font-weight-bold">Update category</button>
               
            </form>
        </div>
    </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

django_pos/templates/products/products_update.html
{% extends "pos/base.html" %}

<!-- Page title  -->
{% block title %}Update product{% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

<!-- Page Heading -->
{% block heading %}Update product{% endblock heading %}

<!-- Page content  -->
{% block content %}
<!--Go back-->
<div class="row ml-0 mb-3">
    <a href="{% url 'products:products_list' %}">
        <button type="button" class="btn btn-info font-weight-bold">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            Go back
        </button>
    </a>
</div>

<div class="row">
    <div class="card col-md-8">
        <div class="card-body">
            <form action="{% url 'products:products_update' product.id %}"  method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-8">
                        <label for="inputDescription">Name</label>
                        <input type="text" class="form-control" name="name" value="{{product.name}}" required>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="state">State</label>
                        <select name="state" class="form-control" required>
                            {% for status in product_status %}
                                {% if status.0 == product.status   %}
                                <option value="{{status.0}}" selected>{{status.1}}</option>
                                {% else %}
                                <option value="{{status.0}}">{{status.1}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-8">
                        <label for="inputDescription">Description</label>
                        <input type="text" name="description" class="form-control" value="{{product.description}}" required>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="category">Category</label>
                        <select name="category" class="form-control" required>
                            <option value="" selected disabled hidden>Select the category</option>
                            {% for category in categories %}
                                {% if product.category.id == category.id%}
                                <option value="{{category.id}}" selected>{{category.name}}</option>
                                {% else %}
                                <option value="{{category.id}}">{{category.name}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-8">
                        <label for="inputPrice">Price (Rs)</label>
                        <input type="number" name="price" step="0.01" min="0" class="form-control" value="{{product.price}}" required>
                        <small class="form-text text-muted">Enter price in rupees with up to 2 decimal places</small>
                    </div>
                </div>
                

                <button type="submit" class="btn btn-success font-weight-bold">Update product</button>
               
            </form>
        </div>
    </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}