django_pos/authentication/urls.py
from django.urls import path
from .views import login_view, register_user, otp_password_reset_request, otp_password_reset_verify
from django.contrib.auth.views import LogoutView

app_name = "authentication"
urlpatterns = [
    path('accounts/login/', login_view, name="login"),
    path('accounts/register/', register_user, name="register"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
         
    # OTP-based password reset URLs
    path('accounts/password-reset/', 
         otp_password_reset_request, 
         name='otp_password_reset_request'),
    path('accounts/password-reset/verify/', 
         otp_password_reset_verify, 
         name='otp_password_reset_verify'),
]

django_pos/customers/urls.py
from django.urls import path

from . import views

app_name = "customers"
urlpatterns = [
    # List customers
    path('', views.customers_list_view, name='customers_list'),
    # Add customer
    path('add', views.customers_add_view, name='customers_add'),
    # Update customer
    path('update/<str:customer_id>',
         views.customers_update_view, name='customers_update'),
    # Delete customer
    path('delete/<str:customer_id>',
         views.customers_delete_view, name='customers_delete'),
]

django_pos/django_pos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # Authentication: Login and Logout
    path('', include('authentication.urls')),
    # Index
    path('', include('pos.urls')),
    # Products
    path('products/', include('products.urls')),
    # Customers
    path('customers/', include('customers.urls')),
    # Sales
    path('sales/', include('sales.urls')),
]

django_pos/pos/urls.py
from django.urls import path

from . import views

app_name = "pos"
urlpatterns = [
    path('', views.index, name='index'),
]

django_pos/products/urls.py
from django.urls import path

from . import views

app_name = "products"
urlpatterns = [
    # List categories
    path('categories', views.categories_list_view, name='categories_list'),
    # Add category
    path('categories/add', views.categories_add_view, name='categories_add'),
    # Update category
    path('categories/update/<str:category_id>',
         views.categories_update_view, name='categories_update'),
    # Delete category
    path('categories/delete/<str:category_id>',
         views.categories_delete_view, name='categories_delete'),

    # List products
    path('', views.products_list_view, name='products_list'),
    # Add product
    path('add', views.products_add_view, name='products_add'),
    # Update product
    path('update/<str:product_id>',
         views.products_update_view, name='products_update'),
    # Delete product
    path('delete/<str:product_id>',
         views.products_delete_view, name='products_delete'),
    # Get products AJAX
    path("get", views.get_products_ajax_view, name="get_products"),
]

django_pos/sales/urls.py
from django.urls import path

from . import views

app_name = "sales"
urlpatterns = [
    # List sales
    path('', views.sales_list_view, name='sales_list'),
    # Add sale
    path('add', views.sales_add_view, name='sales_add'),
    # Details sale
    path('details/<str:sale_id>',
         views.sales_details_view, name='sales_details'),
    # Sale receipt PDF
    path("pdf/<str:sale_id>",
         views.receipt_pdf_view, name="sales_receipt_pdf"),
]

django_pos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Include the default password reset URLs from Django's auth system
    path('accounts/', include('django.contrib.auth.urls')),
]

django_pos/pos/models.py
from django.db import models

# Create your models here.

django_pos/pos/views.py
import json
from datetime import date
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, FloatField, F
from django.db.models.functions import Coalesce
from django.shortcuts import render
from products.models import Product, Category
from sales.models import Sale


@login_required(login_url="/accounts/login/")
def index(request):
    today = date.today()

    year = today.year
    monthly_earnings = []

    # Calculate earnings per month
    for month in range(1, 13):
        earning = Sale.objects.filter(date_added__year=year, date_added__month=month).aggregate(
            total_variable=Coalesce(Sum(F('grand_total')), 0.0, output_field=FloatField())).get('total_variable')
        monthly_earnings.append(earning)

    # Calculate annual earnings (without Rs prefix, will be added in template)
    annual_earnings = Sale.objects.filter(date_added__year=year).aggregate(total_variable=Coalesce(
        Sum(F('grand_total')), 0.0, output_field=FloatField())).get('total_variable')
    annual_earnings = format(annual_earnings, '.2f')

    # AVG per month (without Rs prefix, will be added in template)
    avg_month = format(sum(monthly_earnings)/12, '.2f')

    # Top-selling products
    top_products = Product.objects.annotate(quantity_sum=Sum(
        'saledetail__quantity')).order_by('-quantity_sum')[:3]

    top_products_names = []
    top_products_quantity = []

    for p in top_products:
        top_products_names.append(p.name)
        top_products_quantity.append(p.quantity_sum)

    context = {
        "active_icon": "dashboard",
        "products": Product.objects.all().count(),
        "categories": Category.objects.all().count(),
        "annual_earnings": annual_earnings,
        "monthly_earnings": json.dumps(monthly_earnings),
        "avg_month": avg_month,
        "top_products_names": json.dumps(top_products_names),
        "top_products_names_list": top_products_names,
        "top_products_quantity": json.dumps(top_products_quantity),
    }
    return render(request, "pos/index.html", context)

django_pos/templates/pos/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Smart POS - Point of Sale System">
    <meta name="author" content="">

    <title>Smart POS - {% block title %}{% endblock %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <!--Favicon-->
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}"/>

    {% block stylesheets %}{% endblock stylesheets %}

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        {% include 'pos/sidebar.html' %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                {% include 'pos/navbar.html' %}
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">{% block heading %}{% endblock %}</h1>
                    </div>

                    <!--Messages will appear here-->
                    {% include 'pos/messages.html' with messages=messages%}

                    <!--Page content goes here-->
                    {% block content %}{% endblock content %}


                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            {% include 'pos/footer.html' %}
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    {% include 'pos/logout_modal.html' %}
    <!-- End ofLogout Modal-->


    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!--JavaScript to dissapear messagess automatically-->
    {% comment %} <script type='text/javascript' src="{% static 'js/dissapear_messages.js' %}"></script> {% endcomment %}

    <!-- Page level custom scripts -->
    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}

</body>

</html>

django_pos/templates/pos/footer.html
{% load static %}

<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; <a href="https://github.com/betofleitass/smart-pos">Smart POS</a> <strong id='year'></strong></span>
        </div>
    </div>
    <script>
        let year_el = document.getElementById('year');
        let date = new Date()
        year_el.innerText = date.getFullYear().toString();
    </script>
</footer>

django_pos/templates/pos/index.html
{% extends "pos/base.html" %}
{% load static %}
<!-- Page title  -->
{% block title %}Dashboard{% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

<!-- Page Heading -->
{% block heading %}Dashboard{% endblock heading %}

<!-- Page content  -->
{% block content %}
<!-- Content Row -->
<div class="row">

    <!-- Earnings (Monthly) Card  -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Avg Earning per Month
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            Rs {{ avg_month }} <!-- Display the formatted avg_month -->
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Earnings (Annual) Card  -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Earnings (Annual)
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            Rs {{ annual_earnings }} <!-- Directly use the formatted earnings -->
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-rupee-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <!-- Products Card -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Registered Products
                        </div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{products}}</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-fw fa-tag fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Categories Card -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Registered Categories
                        </div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{categories}}</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-fw fa-tag fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- Content Row -->
<div class="row">

    <!-- Area Chart -->
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Year Earnings Overview</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="chart-area">
                    <canvas id="myAreaChart"></canvas>
                </div>
            </div>
        </div>
    </div>

    <!-- Pie Chart -->
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Best selling products</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="chart-pie pt-4 pb-2">
                    <canvas id="myPieChart"></canvas>
                </div>
                <div class="mt-4 text-center small">
                    <div class="mr-2">
                        <i class="fas fa-circle text-primary mr-2"></i>{{top_products_names_list.0}}
                    </div>
                    <div class="mr-2 mt-2">
                        <i class="fas fa-circle text-success mr-2"></i>{{top_products_names_list.1}}
                    </div>
                    <div class="mr-2 mt-2">
                        <i class="fas fa-circle text-info mr-2"></i>{{top_products_names_list.2}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<!--Chart JS-->
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
<!--Monthly earnings variable-->
<input type="hidden" id="monthly_earnings"  value="{{monthly_earnings|safe}}">
<!--Top products names variable-->
<input type="hidden" id="top_products_names"  value="{{top_products_names}}">
<!--Top products quantity variable-->
<input type="hidden" id="top_products_quantity"  value="{{top_products_quantity|safe}}">
<!--Chart area-->
<script src="{% static 'js/chart-area.js' %}"></script>
<!--Chart pie-->
<script src="{% static 'js/chart-pie.js' %}"></script>
{% endblock javascripts %}

django_pos/templates/pos/logout_modal.html
{% load static %}

<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer"> 
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{% url 'authentication:logout' %}">Logout</a>
            </div>
        </div>
    </div>
</div>

django_pos/templates/pos/messages.html
{% load static %}
<!--Messages-->
{% if messages %}
<div class="form-group">
    {% for message in messages %}
    <div id="message_js" class="alert alert-{{message.extra_tags}} alert-dissmissible fade-show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    {% endfor %}
</div>     
{% endif %}

django_pos/templates/pos/navbar.html
{% load static %}

<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.username}}</span>
                <img class="img-profile rounded-circle"
                    src="{% static 'img/undraw_profile.svg' %}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                {% comment %} <div class="dropdown-divider"></div> {% endcomment %}
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>

django_pos/templates/pos/sidebar.html
{% load static %}

<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'pos:index' %}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-cash-register"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Smart POS</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider  mb-0">

    <!-- Nav Item - Dashboard -->
    <li class="{% if "dashboard" in active_icon %} nav-item active {% else %} nav-item {% endif %}">
        <a class="nav-link" href="{% url 'pos:index' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Products Collapse Menu -->
    <li class="{% if "products" in active_icon %} nav-item active {% else %} nav-item {% endif %}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-tag"></i>
            <span>Products</span>
        </a>
        <div id="collapseTwo" class="{% if "products" in active_icon %} collapse show {% else %} collapse {% endif %}" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="{% if "categories" in active_icon %} collapse-item active {% else %} collapse-item {% endif %}" href="{% url 'products:categories_list' %}">Categories</a>
                <a class="{% if "products_products" in active_icon %} collapse-item active {% else %} collapse-item {% endif %}" href="{% url 'products:products_list' %}">Products</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Customers -->
    <li class="{% if "customers" in active_icon %} nav-item active {% else %} nav-item {% endif %}">
        <a class="nav-link" href="{% url 'customers:customers_list' %}">
            <i class="fas fa-fw fa-users"></i>
            <span>Customers</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Sales -->
    <li class="{% if "sales" in active_icon %} nav-item active {% else %} nav-item {% endif %}">
        <a class="nav-link" href="{% url 'sales:sales_list' %}">
            <i class="fas fa-fw fa-cart-plus"></i>
            <span>Sales</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>


</ul>